### ISSUE TITLE
Variable Handling Error

### ISSUE THREAD

**Issue by Gandalfalex** [ixolius/schlagdieki#1]
initialScreen.lua:20 attempt to perform arithmetic on local "result" (a string value)

Traceback:
initialScreen.lua:20: in function 'callback'
panel.lua:60: in function 'click'
main.lua:77: in function <main.lua:76>
[C]: in function 'xpcall'

after pressing the start button, the program crashes. I cant rly help you here since i don't know lua quite well

**Comment by ixolius** [comment]
This is probably related to the fact that I excluded the simulation program from the repo. It works on my PC. I'll update the gitignore, so that a clone will give you an out-of-the-box-working program. Please pull and tell me if it works.

**Comment by Gandalfalex** [comment]
Now it works perfectly. Thanks!
