### ISSUE TITLE
empty element at the bottom of the screen

### ISSUE THREAD

**Issue by Gandalfalex** [ixolius/schlagdieki#2]
i am not sure if it is a bug or just an element that cant be triggered right now, but at the bottom right, there is an empty element that wasn't there in the original version.

I just wanna know if that one is intended and serves any purpose?

**Comment by ixolius** [comment]
This element will normally show the ranking between the results once the first result is calculated. I will text to display at the start of the program

**Comment by Gandalfalex** [comment]
thanks. I just wasn't sure about this one
